### ISSUE TITLE
No translation available for French (fr)

### ISSUE THREAD

**Issue by sebrock** [sebrock/banano-cam#2]
No translation available for French (fr)

**Solution**:
 Amend /scripts/localization.json

**Note**: please make sure that in each section each line but the last has a trailing comma.
Example:
```
{
  "languages": {
    "en": "English",
    "es": "Español",
    "de": "Deutsch",
    "xx": "NewLanguage"	
  }, 
```
 
 Adds a new language called NewLanguage with identifier xx.

**Comment by libertyseed** [comment]
Hi

**Comment by sebrock** [comment]
merged. Thanks to @libertyseed
